apiVersion: v1
kind: ConfigMap
metadata:
  name: &app-name go-inventory-cm
  namespace: test-a
  labels:
    app: *app-name
data:
  VERSION: "1.0"
  ACCOUNT: "aws:908671954593"
  APP_NAME: "go-inventory.arch-eks-01-02"
  PORT: "7000"
  ENV: "dev"

  DB_HOST: "rds-proxy-db-arch.proxy-couoacqalfwt.us-east-2.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_MAX_CONNECTION: "10"
  CTX_TIMEOUT: "5"

  LOG_LEVEL: "info" #info, error, warning
  OTEL_EXPORTER_OTLP_ENDPOINT: "localhost:4317"

  OTEL_METRICS: "false"
  OTEL_STDOUT_TRACER: "false"
  OTEL_TRACES: "false"

  OTEL_LOGS: "false"
  OTEL_STDOUT_LOG_GROUP: "false"
  LOG_GROUP: "/mnt/c/Eliezer/log/go-inventory.log"