apiVersion: v1
kind: ConfigMap
metadata:
  name: &app-name go-inventory-cm
  namespace: test-a
  labels:
    app: *app-name
data:
  VERSION: "1.1"
  ACCOUNT: "aws:908671954593"
  APP_NAME: "go-inventory.arch-eks-01-02"
  PORT: "7000"
  ENV: "dev"

  DB_HOST: "rds-proxy-db-arch.proxy-couoacqalfwt.us-east-2.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_MAX_CONNECTION: "10"
  CTX_TIMEOUT: "5"

  LOG_LEVEL: "warning" #info, error, warn
  OTEL_EXPORTER_OTLP_ENDPOINT: "arch-eks-01-02-otel-collector.default.svc.cluster.local:4317"

  OTEL_METRICS: "true"
  OTEL_STDOUT_TRACER: "false"
  OTEL_TRACES: "true"

  # the features below works only for a local machine, for kubernetes all logs are shipping via a collector
  OTEL_LOGS: "false"
  OTEL_STDOUT_LOG_GROUP: "false"
  LOG_GROUP: "/dock/eks/arch-eks-01-02/test-a/go-inventory"