name: Deploy Workload in EKS

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      AWS_ACCOUNT_ID:
        description: 'AWS account id'
        required: true
        default: '908671954593'
      REGION:
        description: 'AWS Region'
        required: true
        default: 'us-east-2'

env:
  GO_VERSION: 1.24

defaults:
  run:
    shell: bash

permissions:
  id-token: write   # Isso é necessário para solicitar o JWT
  contents: read    # Isso é necessário para ações/checkout    

jobs:
  setup-environment:
    uses: ./.github/workflows/setup-environment.yaml
    with:
      AWS_ACCOUNT_ID: ${{ github.event.inputs.AWS_ACCOUNT_ID }}
      REGION: ${{ github.event.inputs.REGION }}

  build:
    runs-on: ubuntu-latest
    needs: [ setup-environment ]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup go env
      uses: actions/setup-go@v5.0.2
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Install dependencies
      run: go mod tidy

    - name: Build image
      env:
        REPO_NAME: ${{ needs.setup-environment.outputs.REPO_NAME }}
        MAIN_GO_FILE: ${{ needs.setup-environment.outputs.MAIN_GO_FILE }}
      run: go build -v -o $REPO_NAME $MAIN_GO_FILE

  package-and-publish:
    runs-on: ubuntu-latest
    needs: [ setup-environment, build ]
    permissions:
      id-token: write
      contents: read
    outputs:
        REGISTRY: ${{ steps.set-registry-output.outputs.REGISTRY }}
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials - OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::908671954593:role/oidc-gitaction
          aws-region: ${{ needs.setup-environment.outputs.AWS_REGION }}

      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set REGISTRY output
        id: set-registry-output
        run: echo "REGISTRY=${{ steps.login-ecr.outputs.registry }}" >> "$GITHUB_OUTPUT"

      - name: Build, tag, and push Docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ needs.setup-environment.outputs.REPO_NAME }}
          REGION: ${{ needs.setup-environment.outputs.AWS_REGION }}
          IMAGE_TAG: ${{ needs.setup-environment.outputs.IMAGE_TAG }}
        run: | # Check if repository already exists.
          aws ecr describe-repositories --repository-names ${REPOSITORY} || aws ecr create-repository --repository-name ${REPOSITORY} --region ${REGION}
          docker build  --build-arg GITHUB_TOKEN=${{ secrets.GH_PIPELINE_TOKEN_ACTIONS }} -t $REGISTRY/$REPOSITORY:$IMAGE_TAG . 
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

